spring.application.name=tiendaweb
spring.web.locale=es_CL
spring.web.locale-resolver=fixed
server.port=8092

# Configuración del Broker de José Clavijo
spring.artemis.broker-url=tcp://localhost:61616
spring.artemis.user=admin
spring.artemis.password=admin123

# Colas estándar del proyecto (nombres unificados)
queue.web.pedidos=jcl_web_pedidos
queue.marketplace.pedidos=jcl_mkp_pedidos
queue.canonical.pedidos=jcl_pedidos
queue.facturacion=jcl_facturacion
queue.facturacion.respuesta=jcl_facturacion_respuesta
queue.bodega=jcl_bodega