spring.application.name=tiendaweb
spring.web.locale=es_CL
spring.web.locale-resolver=fixed
server.port=8092

# Configuración del Broker de José Clavijo
spring.artemis.broker-url=tcp://localhost:61616
spring.artemis.user=admin
spring.artemis.password=admin123

# Colas (usar prefijo jcl_)
# Cola donde la Tienda Web publica pedidos en su formato XML
queue.web.pedidos=jcl_web_pedidos

# Alias para Marketplace (mantengo ambos nombres para compatibilidad)
queue.mkp.pedidos=jcl_mkp_pedidos
queue.marketplace.pedidos=${queue.mkp.pedidos}

# Cola que representará el canal canónico central (JSON canónico)
# En broker.xml esto corresponde a jcl_pedidos
queue.canonical.pedidos=jcl_pedidos
queue.pedidos=${queue.canonical.pedidos}

# Cola para facturación / sistema legacy
queue.facturacion=jcl_facturacion
# Cola donde el legacy responde (ACK / confirmación)
queue.facturacion.respuesta=jcl_facturacion_respuesta

# Cola para Bodega (Warehouse)
queue.bodega.pedidos=jcl_bodega

# Opcional: base URL del servicio Marketplace (si lo vas a consultar para enriquecer)
marketplace.base-url=http://localhost:8091
# Control de comportamiento adicional
marketplace.poll.enabled=false

# Otros ajustes (opcionales / recomendados)
# Asegura persistencia y comportamiento JMS por defecto (puedes ajustar si es necesario)
spring.jms.listener.acknowledge-mode=auto