spring.application.name=tiendaweb
spring.web.locale=es_CL
spring.web.locale-resolver=fixed
server.port=8092

# Configuración del Broker de José Clavijo
spring.artemis.broker-url=tcp://localhost:61616
spring.artemis.user=admin
spring.artemis.password=admin123

# El nombre de la cola (usa las iniciales jcl)
queue.web.pedidos=jcl_web_pedidos

# cola de salida con mensajes en formato canónico (JSON)
queue.canonical.pedidos=jcl_canonical_pedidos

queue.marketplace.pedidos=jcl_marketplace_pedidos
queue.facturacion=jcl_facturacion